require("defaults")
require("mappings").load()
require("settings").load()
require("autocmds").load()
local plugins = require("plugins")
local loader = require("loader").init()
loader:load({ plugins, loader.user_plugins })
require("colors")
