require("globals")
require("mappings")
require("settings")
require("autocmd")
local plugins = require("plugins")
local loader = require("loader").init()
loader:load({ plugins, loader.user_plugins })
require("colors")
