local nvlx = {
    general = {},
    disabled = {
        builtin_plugins = {},
        plugins = {},
    },
    options = {},
    highlights = {},
    maps = {
        general = {
            command = {},
            insert = {},
            normal = {},
            object = {},
            terminal = {},
            visual = {},
            visual_block = {},
        },
        leader = {},
    },
    autocmds = {},
    plugins = {},
    config = {
        plugins = {
            autopairs = {},
            autosave = {},
            bufferline = {},
            colorizer = {},
            compe = {},
            feline = {},
            gitsigns = {},
            indent_blankline = {},
            persistence = {},
            telescope = {},
            toggleterm = {},
            treesitter = {},
            whichkey = {},
        },
        plugins_override = {
            autopairs = {},
            autosave = {},
            bufferline = {},
            colorizer = {},
            compe = {},
            feline = {},
            gitsigns = {},
            indent_blankline = {},
            persistence = {},
            telescope = {},
            toggleterm = {},
            treesitter = {},
            whichkey = {},
        },
    },
}
return nvlx
