name: Install on ubuntu-latest
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install neovim
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/v0.5.0/nvim.appimage
          chmod u+x nvim.appimage
          sudo mv nvim.appimage /usr/bin/nvim
      - name: Run install script
        run: ./utils/install.sh --ci
      - name: Check for errors
        run: if nvim --headless -c ':qall' 2>&1| grep 'Error'; then false; fi
      - name: Check PackerCompile
        run: if nvim --headless +PackerCompile -c ':qall' 2>&1| grep 'Error'; then false; fi
      - name: Check checkhealth
        run: if nvim --headless +checkhealth -c ':qall' 2>&1| grep 'Error'; then false; fi
