name: Install on ubuntu-latest
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install NVelox
        timeout-minutes: 10
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake gcc-11 gettext gperf libtool-bin locales ninja-build pkg-config unzip libluajit-5.1-dev libacl1-dev libmsgpack-dev libnss-wrapper libtermkey-dev lib-tree-sitter-dev libunibilium-dev libuv1-dev
          mkdir build
          cd build
          cmake -Gninja ..
          sudo ninja
