name: Install on ubuntu-latest
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: add-ci
      - name: Add neovim ppa
        timeout-minutes: 10
        run: |
          sudo add-apt-repository ppa:neovim-ppa/stable
          sudo apt-get update
      - name: Run install script
        run: ./utils/install.sh --ci
      - name: Check for errors
        run: ./utils/check.sh
