name: Install on ubuntu-latest
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Add neovim-ppa
        run: sudo add-apt-repository ppa:neovim-ppa/unstable && sudo apt-get update
      - name: Run install script
        run: ./utils/install.sh --ci
      - name: Check for errors
        run: if nvim --headless -c ':qall' 2>&1| grep 'Error'; then false; fi
      - name: Check PackerCompile
        run: if nvim --headless +PackerCompile -c ':qall' 2>&1| grep 'Error'; then false; fi
      - name: Check checkhealth
        run: if nvim --headless +checkhealth -c ':qall' 2>&1| grep 'Error'; then false; fi
