name: Install on ubuntu-latest
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install neovim
        timeout-minutes: 10
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake gcc-11 gettext gperf libtool-bin locales ninja-build pkg-config unzip
          cd external/nvelox-neovim && CC=gcc-11 make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH="
      - name: Install NVelox
        run: |
          ln -s "$PWD" "$HOME/.config/nvim"
          cd "$HOME/.config/nvim"
          make
      - name: Check for errors in checkhealth
        run: |
          make NVIM_PATH=~/neovim/build/bin/nvim debug
          ./tools/check.sh
