name: Install on ubuntu-latest
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: add-ci
      - name: Install neovim
        timeout-minutes: 10
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/v0.5.0/nvim-linux64.tar.gz
          tar -xvf nvim-linux64.tar.gz
          cd nvim-linux64
          sudo mv bin/nvim /usr/bin/nvim
      - name: Run install script
        run: ./utils/install.sh --ci
      - name: Check for errors
        run: ./utils/check.sh
