name: Install on ubuntu-latest
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install neovim
        timeout-minutes: 10
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/v0.5.0/nvim-linux64.tar.gz
          tar -xvf nvim-linux64.tar.gz
          cp -r nvim-linux64 ~/.local 
      - name: Install NVelox
        run: |
          sudo apt install ripgrep
          ln -s "$PWD" "$HOME/.config/nvim"
          mkdir "$HOME/.config/nvlx"
          touch "$HOME/.config/nvlx/init.lua"
          git clone https://github.com/wbthomason/packer.nvim "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"
          nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      - name: Check for errors
        run: ./utils/check.sh
